### ISSUE TITLE
Output tsv file

### ISSUE THREAD

**Issue by Jordano700** [Noble-Lab/cascadia#2]
Hello, I have run the script on the demo mzML file and as output I am only getting 3 columns like so : 
![image](https://github.com/user-attachments/assets/c5a9ac3f-ee1f-4061-9c1b-25b1b5d0d75a)

I'm getting the peptide sequence, then a bunch of K's, and then what I would assume is the predicted score/confidence.

**Comment by justin-a-sanders** [comment]
Hi Jordan, 

It looks like you caught a version of Cascadia that was mid-development. The current main branch and release through PIP should give results which match the expected output described in the documentation.
